version: "3.8"
services:
    werobot:
        image: werobot:latest
        build: .
        container_name: werobot
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./app:/deploy/app